package Model;
// Generated 1/03/2015 06:26:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EspecificacionesVarias generated by hbm2java
 */
@Entity
@Table(name="especificaciones_varias"
    ,catalog="inmobiliaria"
)
public class EspecificacionesVarias  implements java.io.Serializable {


     private Integer idEspecificacionesVarias;
     private String nombreEspecificiacionesVarias;
     private Set<InformacionPrincipalHasEspecificacionesVarias> informacionPrincipalHasEspecificacionesVariases = new HashSet<InformacionPrincipalHasEspecificacionesVarias>(0);

    public EspecificacionesVarias() {
    }

	
    public EspecificacionesVarias(String nombreEspecificiacionesVarias) {
        this.nombreEspecificiacionesVarias = nombreEspecificiacionesVarias;
    }
    public EspecificacionesVarias(String nombreEspecificiacionesVarias, Set<InformacionPrincipalHasEspecificacionesVarias> informacionPrincipalHasEspecificacionesVariases) {
       this.nombreEspecificiacionesVarias = nombreEspecificiacionesVarias;
       this.informacionPrincipalHasEspecificacionesVariases = informacionPrincipalHasEspecificacionesVariases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_especificaciones_varias", unique=true, nullable=false)
    public Integer getIdEspecificacionesVarias() {
        return this.idEspecificacionesVarias;
    }
    
    public void setIdEspecificacionesVarias(Integer idEspecificacionesVarias) {
        this.idEspecificacionesVarias = idEspecificacionesVarias;
    }

    
    @Column(name="nombre_especificiaciones_varias", nullable=false, length=45)
    public String getNombreEspecificiacionesVarias() {
        return this.nombreEspecificiacionesVarias;
    }
    
    public void setNombreEspecificiacionesVarias(String nombreEspecificiacionesVarias) {
        this.nombreEspecificiacionesVarias = nombreEspecificiacionesVarias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="especificacionesVarias")
    public Set<InformacionPrincipalHasEspecificacionesVarias> getInformacionPrincipalHasEspecificacionesVariases() {
        return this.informacionPrincipalHasEspecificacionesVariases;
    }
    
    public void setInformacionPrincipalHasEspecificacionesVariases(Set<InformacionPrincipalHasEspecificacionesVarias> informacionPrincipalHasEspecificacionesVariases) {
        this.informacionPrincipalHasEspecificacionesVariases = informacionPrincipalHasEspecificacionesVariases;
    }




}


