package Model;
// Generated 1/03/2015 06:26:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NumeroAlcobas generated by hbm2java
 */
@Entity
@Table(name="numero_alcobas"
    ,catalog="inmobiliaria"
)
public class NumeroAlcobas  implements java.io.Serializable {


     private Integer idNumeroAlcobas;
     private String cantidadAlcobas;
     private Set<InformacionPrincipal> informacionPrincipals = new HashSet<InformacionPrincipal>(0);

    public NumeroAlcobas() {
    }

	
    public NumeroAlcobas(String cantidadAlcobas) {
        this.cantidadAlcobas = cantidadAlcobas;
    }
    public NumeroAlcobas(String cantidadAlcobas, Set<InformacionPrincipal> informacionPrincipals) {
       this.cantidadAlcobas = cantidadAlcobas;
       this.informacionPrincipals = informacionPrincipals;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_numero_alcobas", unique=true, nullable=false)
    public Integer getIdNumeroAlcobas() {
        return this.idNumeroAlcobas;
    }
    
    public void setIdNumeroAlcobas(Integer idNumeroAlcobas) {
        this.idNumeroAlcobas = idNumeroAlcobas;
    }

    
    @Column(name="cantidad_alcobas", nullable=false, length=10)
    public String getCantidadAlcobas() {
        return this.cantidadAlcobas;
    }
    
    public void setCantidadAlcobas(String cantidadAlcobas) {
        this.cantidadAlcobas = cantidadAlcobas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="numeroAlcobas")
    public Set<InformacionPrincipal> getInformacionPrincipals() {
        return this.informacionPrincipals;
    }
    
    public void setInformacionPrincipals(Set<InformacionPrincipal> informacionPrincipals) {
        this.informacionPrincipals = informacionPrincipals;
    }




}


