package Model;
// Generated 1/03/2015 06:26:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NumeroBanios generated by hbm2java
 */
@Entity
@Table(name="numero_banios"
    ,catalog="inmobiliaria"
)
public class NumeroBanios  implements java.io.Serializable {


     private Integer idNumeroBanios;
     private String cantidadBanios;
     private Set<InformacionPrincipal> informacionPrincipals = new HashSet<InformacionPrincipal>(0);

    public NumeroBanios() {
    }

	
    public NumeroBanios(String cantidadBanios) {
        this.cantidadBanios = cantidadBanios;
    }
    public NumeroBanios(String cantidadBanios, Set<InformacionPrincipal> informacionPrincipals) {
       this.cantidadBanios = cantidadBanios;
       this.informacionPrincipals = informacionPrincipals;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_numero_banios", unique=true, nullable=false)
    public Integer getIdNumeroBanios() {
        return this.idNumeroBanios;
    }
    
    public void setIdNumeroBanios(Integer idNumeroBanios) {
        this.idNumeroBanios = idNumeroBanios;
    }

    
    @Column(name="cantidad_banios", nullable=false, length=15)
    public String getCantidadBanios() {
        return this.cantidadBanios;
    }
    
    public void setCantidadBanios(String cantidadBanios) {
        this.cantidadBanios = cantidadBanios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="numeroBanios")
    public Set<InformacionPrincipal> getInformacionPrincipals() {
        return this.informacionPrincipals;
    }
    
    public void setInformacionPrincipals(Set<InformacionPrincipal> informacionPrincipals) {
        this.informacionPrincipals = informacionPrincipals;
    }




}


