package Model;
// Generated 1/03/2015 06:26:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NumeroPlantas generated by hbm2java
 */
@Entity
@Table(name="numero_plantas"
    ,catalog="inmobiliaria"
)
public class NumeroPlantas  implements java.io.Serializable {


     private Integer idNumeroPlantas;
     private String cantidadPlantas;
     private Set<InformacionPrincipal> informacionPrincipals = new HashSet<InformacionPrincipal>(0);

    public NumeroPlantas() {
    }

	
    public NumeroPlantas(String cantidadPlantas) {
        this.cantidadPlantas = cantidadPlantas;
    }
    public NumeroPlantas(String cantidadPlantas, Set<InformacionPrincipal> informacionPrincipals) {
       this.cantidadPlantas = cantidadPlantas;
       this.informacionPrincipals = informacionPrincipals;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_numero_plantas", unique=true, nullable=false)
    public Integer getIdNumeroPlantas() {
        return this.idNumeroPlantas;
    }
    
    public void setIdNumeroPlantas(Integer idNumeroPlantas) {
        this.idNumeroPlantas = idNumeroPlantas;
    }

    
    @Column(name="cantidad_plantas", nullable=false, length=10)
    public String getCantidadPlantas() {
        return this.cantidadPlantas;
    }
    
    public void setCantidadPlantas(String cantidadPlantas) {
        this.cantidadPlantas = cantidadPlantas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="numeroPlantas")
    public Set<InformacionPrincipal> getInformacionPrincipals() {
        return this.informacionPrincipals;
    }
    
    public void setInformacionPrincipals(Set<InformacionPrincipal> informacionPrincipals) {
        this.informacionPrincipals = informacionPrincipals;
    }




}


