package Model;
// Generated 1/03/2015 06:26:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Parqueadero generated by hbm2java
 */
@Entity
@Table(name="parqueadero"
    ,catalog="inmobiliaria"
)
public class Parqueadero  implements java.io.Serializable {


     private Integer idParqueadero;
     private String cantidadParqueaderos;
     private Set<InformacionPrincipal> informacionPrincipals = new HashSet<InformacionPrincipal>(0);

    public Parqueadero() {
    }

	
    public Parqueadero(String cantidadParqueaderos) {
        this.cantidadParqueaderos = cantidadParqueaderos;
    }
    public Parqueadero(String cantidadParqueaderos, Set<InformacionPrincipal> informacionPrincipals) {
       this.cantidadParqueaderos = cantidadParqueaderos;
       this.informacionPrincipals = informacionPrincipals;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_parqueadero", unique=true, nullable=false)
    public Integer getIdParqueadero() {
        return this.idParqueadero;
    }
    
    public void setIdParqueadero(Integer idParqueadero) {
        this.idParqueadero = idParqueadero;
    }

    
    @Column(name="cantidad_parqueaderos", nullable=false, length=10)
    public String getCantidadParqueaderos() {
        return this.cantidadParqueaderos;
    }
    
    public void setCantidadParqueaderos(String cantidadParqueaderos) {
        this.cantidadParqueaderos = cantidadParqueaderos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="parqueadero")
    public Set<InformacionPrincipal> getInformacionPrincipals() {
        return this.informacionPrincipals;
    }
    
    public void setInformacionPrincipals(Set<InformacionPrincipal> informacionPrincipals) {
        this.informacionPrincipals = informacionPrincipals;
    }




}


