package Model;
// Generated 1/03/2015 06:26:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RangoPreciosAjustado generated by hbm2java
 */
@Entity
@Table(name="rango_precios_ajustado"
    ,catalog="inmobiliaria"
)
public class RangoPreciosAjustado  implements java.io.Serializable {


     private Integer idRangoPreciosAjustado;
     private RangoPrecios rangoPrecios;
     private TipoOperacion tipoOperacion;
     private Set<InformacionPrincipal> informacionPrincipals = new HashSet<InformacionPrincipal>(0);

    public RangoPreciosAjustado() {
    }

	
    public RangoPreciosAjustado(RangoPrecios rangoPrecios, TipoOperacion tipoOperacion) {
        this.rangoPrecios = rangoPrecios;
        this.tipoOperacion = tipoOperacion;
    }
    public RangoPreciosAjustado(RangoPrecios rangoPrecios, TipoOperacion tipoOperacion, Set<InformacionPrincipal> informacionPrincipals) {
       this.rangoPrecios = rangoPrecios;
       this.tipoOperacion = tipoOperacion;
       this.informacionPrincipals = informacionPrincipals;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_rango_precios_ajustado", unique=true, nullable=false)
    public Integer getIdRangoPreciosAjustado() {
        return this.idRangoPreciosAjustado;
    }
    
    public void setIdRangoPreciosAjustado(Integer idRangoPreciosAjustado) {
        this.idRangoPreciosAjustado = idRangoPreciosAjustado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rango_precios_id_rango_precios", nullable=false)
    public RangoPrecios getRangoPrecios() {
        return this.rangoPrecios;
    }
    
    public void setRangoPrecios(RangoPrecios rangoPrecios) {
        this.rangoPrecios = rangoPrecios;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo_operacion_id_tipo_operacion", nullable=false)
    public TipoOperacion getTipoOperacion() {
        return this.tipoOperacion;
    }
    
    public void setTipoOperacion(TipoOperacion tipoOperacion) {
        this.tipoOperacion = tipoOperacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rangoPreciosAjustado")
    public Set<InformacionPrincipal> getInformacionPrincipals() {
        return this.informacionPrincipals;
    }
    
    public void setInformacionPrincipals(Set<InformacionPrincipal> informacionPrincipals) {
        this.informacionPrincipals = informacionPrincipals;
    }




}


