package Model;
// Generated 1/03/2015 06:26:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RangoPrecios generated by hbm2java
 */
@Entity
@Table(name="rango_precios"
    ,catalog="inmobiliaria"
)
public class RangoPrecios  implements java.io.Serializable {


     private Integer idRangoPrecios;
     private String cantidadPrecio;
     private Set<RangoPreciosAjustado> rangoPreciosAjustados = new HashSet<RangoPreciosAjustado>(0);

    public RangoPrecios() {
    }

	
    public RangoPrecios(String cantidadPrecio) {
        this.cantidadPrecio = cantidadPrecio;
    }
    public RangoPrecios(String cantidadPrecio, Set<RangoPreciosAjustado> rangoPreciosAjustados) {
       this.cantidadPrecio = cantidadPrecio;
       this.rangoPreciosAjustados = rangoPreciosAjustados;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_rango_precios", unique=true, nullable=false)
    public Integer getIdRangoPrecios() {
        return this.idRangoPrecios;
    }
    
    public void setIdRangoPrecios(Integer idRangoPrecios) {
        this.idRangoPrecios = idRangoPrecios;
    }

    
    @Column(name="cantidad_precio", nullable=false, length=45)
    public String getCantidadPrecio() {
        return this.cantidadPrecio;
    }
    
    public void setCantidadPrecio(String cantidadPrecio) {
        this.cantidadPrecio = cantidadPrecio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rangoPrecios")
    public Set<RangoPreciosAjustado> getRangoPreciosAjustados() {
        return this.rangoPreciosAjustados;
    }
    
    public void setRangoPreciosAjustados(Set<RangoPreciosAjustado> rangoPreciosAjustados) {
        this.rangoPreciosAjustados = rangoPreciosAjustados;
    }




}


