package Model;
// Generated 1/03/2015 06:26:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name="roles"
    ,catalog="inmobiliaria"
)
public class Roles  implements java.io.Serializable {


     private Integer idRoles;
     private String nombreRol;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Roles() {
    }

	
    public Roles(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    public Roles(String nombreRol, Set<Usuario> usuarios) {
       this.nombreRol = nombreRol;
       this.usuarios = usuarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_roles", unique=true, nullable=false)
    public Integer getIdRoles() {
        return this.idRoles;
    }
    
    public void setIdRoles(Integer idRoles) {
        this.idRoles = idRoles;
    }

    
    @Column(name="nombre_rol", nullable=false, length=45)
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="roles")
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


