package Model;
// Generated 1/03/2015 06:26:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoOperacion generated by hbm2java
 */
@Entity
@Table(name="tipo_operacion"
    ,catalog="inmobiliaria"
)
public class TipoOperacion  implements java.io.Serializable {


     private int idTipoOperacion;
     private String nombreTipoOperacion;
     private Set<RangoPreciosAjustado> rangoPreciosAjustados = new HashSet<RangoPreciosAjustado>(0);
     private Set<InformacionPrincipal> informacionPrincipals = new HashSet<InformacionPrincipal>(0);

    public TipoOperacion() {
    }

	
    public TipoOperacion(int idTipoOperacion, String nombreTipoOperacion) {
        this.idTipoOperacion = idTipoOperacion;
        this.nombreTipoOperacion = nombreTipoOperacion;
    }
    public TipoOperacion(int idTipoOperacion, String nombreTipoOperacion, Set<RangoPreciosAjustado> rangoPreciosAjustados, Set<InformacionPrincipal> informacionPrincipals) {
       this.idTipoOperacion = idTipoOperacion;
       this.nombreTipoOperacion = nombreTipoOperacion;
       this.rangoPreciosAjustados = rangoPreciosAjustados;
       this.informacionPrincipals = informacionPrincipals;
    }
   
     @Id 

    
    @Column(name="id_tipo_operacion", unique=true, nullable=false)
    public int getIdTipoOperacion() {
        return this.idTipoOperacion;
    }
    
    public void setIdTipoOperacion(int idTipoOperacion) {
        this.idTipoOperacion = idTipoOperacion;
    }

    
    @Column(name="nombre_tipo_operacion", nullable=false, length=45)
    public String getNombreTipoOperacion() {
        return this.nombreTipoOperacion;
    }
    
    public void setNombreTipoOperacion(String nombreTipoOperacion) {
        this.nombreTipoOperacion = nombreTipoOperacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoOperacion")
    public Set<RangoPreciosAjustado> getRangoPreciosAjustados() {
        return this.rangoPreciosAjustados;
    }
    
    public void setRangoPreciosAjustados(Set<RangoPreciosAjustado> rangoPreciosAjustados) {
        this.rangoPreciosAjustados = rangoPreciosAjustados;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoOperacion")
    public Set<InformacionPrincipal> getInformacionPrincipals() {
        return this.informacionPrincipals;
    }
    
    public void setInformacionPrincipals(Set<InformacionPrincipal> informacionPrincipals) {
        this.informacionPrincipals = informacionPrincipals;
    }




}


